// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_setting

import (
	"github.com/wujchao/sys-base/api/sys_setting"
)

type ControllerV1 struct{}

func NewV1() sys_setting.ISysSettingV1 {
	return &ControllerV1{}
}
