// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_user

import (
	"sys-base/api/sys_user"
)

type ControllerV1 struct{}

func NewV1() sys_user.ISysUserV1 {
	return &ControllerV1{}
}
