// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_user_oneself

import (
	"github.com/wujchao/sys-base/api/sys_user_oneself"
)

type ControllerV1 struct{}

func NewV1() sys_user_oneself.ISysUserOneselfV1 {
	return &ControllerV1{}
}
