// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_third_party_login

import (
	"sys-base/api/sys_third_party_login"
)

type ControllerV1 struct{}

func NewV1() sys_third_party_login.ISysThirdPartyLoginV1 {
	return &ControllerV1{}
}
