// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_doc

import (
	"github.com/wujchao/sys-base/api/sys_doc"
)

type ControllerV1 struct{}

func NewV1() sys_doc.ISysDocV1 {
	return &ControllerV1{}
}
