// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sys-base/internal/dao/internal"
)

// internalSysRulesDao is internal type for wrapping internal DAO implements.
type internalSysRulesDao = *internal.SysRulesDao

// sysRulesDao is the data access object for table sys_rules.
// You can define custom methods on it to extend its functionality as you wish.
type sysRulesDao struct {
	internalSysRulesDao
}

var (
	// SysRules is globally public accessible object for table sys_rules operations.
	SysRules = sysRulesDao{
		internal.NewSysRulesDao(),
	}
)

// Fill with you ideas below.
