// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sys-base/internal/dao/internal"
)

// internalSysThirdPartyUserDao is internal type for wrapping internal DAO implements.
type internalSysThirdPartyUserDao = *internal.SysThirdPartyUserDao

// sysThirdPartyUserDao is the data access object for table sys_third_party_user.
// You can define custom methods on it to extend its functionality as you wish.
type sysThirdPartyUserDao struct {
	internalSysThirdPartyUserDao
}

var (
	// SysThirdPartyUser is globally public accessible object for table sys_third_party_user operations.
	SysThirdPartyUser = sysThirdPartyUserDao{
		internal.NewSysThirdPartyUserDao(),
	}
)

// Fill with you ideas below.
