// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wujchao/sys-base/internal/dao/internal"
)

// internalSysUsersRoleDao is internal type for wrapping internal DAO implements.
type internalSysUsersRoleDao = *internal.SysUsersRoleDao

// sysUsersRoleDao is the data access object for table sys_users_role.
// You can define custom methods on it to extend its functionality as you wish.
type sysUsersRoleDao struct {
	internalSysUsersRoleDao
}

var (
	// SysUsersRole is globally public accessible object for table sys_users_role operations.
	SysUsersRole = sysUsersRoleDao{
		internal.NewSysUsersRoleDao(),
	}
)

// Fill with you ideas below.
