// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sys-base/internal/dao/internal"
)

// internalSysRoleRulesDao is internal type for wrapping internal DAO implements.
type internalSysRoleRulesDao = *internal.SysRoleRulesDao

// sysRoleRulesDao is the data access object for table sys_role_rules.
// You can define custom methods on it to extend its functionality as you wish.
type sysRoleRulesDao struct {
	internalSysRoleRulesDao
}

var (
	// SysRoleRules is globally public accessible object for table sys_role_rules operations.
	SysRoleRules = sysRoleRulesDao{
		internal.NewSysRoleRulesDao(),
	}
)

// Fill with you ideas below.
