// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wujchao/sys-base/internal/dao/internal"
)

// internalSysSettingDao is internal type for wrapping internal DAO implements.
type internalSysSettingDao = *internal.SysSettingDao

// sysSettingDao is the data access object for table sys_setting.
// You can define custom methods on it to extend its functionality as you wish.
type sysSettingDao struct {
	internalSysSettingDao
}

var (
	// SysSetting is globally public accessible object for table sys_setting operations.
	SysSetting = sysSettingDao{
		internal.NewSysSettingDao(),
	}
)

// Fill with you ideas below.
