// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wujchao/sys-base/internal/dao/internal"
)

// internalSysUsersDao is internal type for wrapping internal DAO implements.
type internalSysUsersDao = *internal.SysUsersDao

// sysUsersDao is the data access object for table sys_users.
// You can define custom methods on it to extend its functionality as you wish.
type sysUsersDao struct {
	internalSysUsersDao
}

var (
	// SysUsers is globally public accessible object for table sys_users operations.
	SysUsers = sysUsersDao{
		internal.NewSysUsersDao(),
	}
)

// Fill with you ideas below.
