// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sys-base/internal/dao/internal"
)

// internalSysDocDao is internal type for wrapping internal DAO implements.
type internalSysDocDao = *internal.SysDocDao

// sysDocDao is the data access object for table sys_doc.
// You can define custom methods on it to extend its functionality as you wish.
type sysDocDao struct {
	internalSysDocDao
}

var (
	// SysDoc is globally public accessible object for table sys_doc operations.
	SysDoc = sysDocDao{
		internal.NewSysDocDao(),
	}
)

// Fill with you ideas below.
