// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wujchao/sys-base/internal/dao/internal"
)

// internalSysRulesI18NDao is internal type for wrapping internal DAO implements.
type internalSysRulesI18NDao = *internal.SysRulesI18NDao

// sysRulesI18NDao is the data access object for table sys_rules_i18n.
// You can define custom methods on it to extend its functionality as you wish.
type sysRulesI18NDao struct {
	internalSysRulesI18NDao
}

var (
	// SysRulesI18N is globally public accessible object for table sys_rules_i18n operations.
	SysRulesI18N = sysRulesI18NDao{
		internal.NewSysRulesI18NDao(),
	}
)

// Fill with you ideas below.
