// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_upload

import (
	"github.com/wujchao/sys-base/api/sys_upload"
)

type ControllerV1 struct{}

func NewV1() sys_upload.ISysUploadV1 {
	return &ControllerV1{}
}
