// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_role

import (
	"sys-base/api/sys_role"
)

type ControllerV1 struct{}

func NewV1() sys_role.ISysRoleV1 {
	return &ControllerV1{}
}
