// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_login

import (
	"github.com/wujchao/sys-base/api/sys_login"
)

type ControllerV1 struct{}

func NewV1() sys_login.ISysLoginV1 {
	return &ControllerV1{}
}
