// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_oneself

import (
	"sys-base/api/sys_oneself"
)

type ControllerV1 struct{}

func NewV1() sys_oneself.ISysOneselfV1 {
	return &ControllerV1{}
}
